inherit_from: configs/TUM_RGBD/tum.yaml
mapping:
  bound: [[-3, 8],[-3.6, 5.9], [-7.9, 4.4]]
  marching_cubes_bound: [[-5.0,13.4],[-5.0,13.7],[-5.0,5.0]]
data:
  input_folder: Datasets/TUM_RGBD/rgbd_dataset_freiburg1_room
  output: output/TUM_RGBD/rgbd_dataset_freiburg1_room
cam:  #intrinsic is different per scene in TUM
  H: 480
  W: 640
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 8
  crop_size: [384,512]
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]